[package]
name = "graph-iso-pfs"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
blake3 = "1.5.0"
perm = { path = "../perm/", features = ["rand"] }
rand = "0.8.5"
rand_chacha = "0.3.1"
serde = { version = "1.0.190", features = ["derive"] }
